<!-- NOTE: This file is a template. Do not edit README.md directly; it is auto-generated by .github/workflows/update-profile.yml using scripts/generate_readme.py. -->
<div align="center">

  <h1 style="margin: 0; font-size: 2.2rem;"><img alt="👋" src="https://em-content.zobj.net/thumbs/120/apple/354/waving-hand_1f44b.png" width="36" height="36" style="vertical-align: -6px; margin-right: 6px;" /> Hey, I'm {{USER_NAME}}</h1>

</div>

### 💻 Top Languages

{{TOP_LANGUAGES}}

### 📊 Metrics

<p align="left">
  <img src="./assets/github-metrics.svg" />
</p>

---

### 👷 Active projects

{{WORKING_ON}}

### 🌱 Latest repositories

{{LATEST_PROJECTS}}

### 🔨 Recent pull requests

{{RECENT_PRS}}

### ⭐ Recent stars

{{RECENT_STARS}}

### Connect

{{SOCIAL_LINKS}}
