<!-- Auto-generated by generate_readme.py - do not edit README.md directly -->

<div align="center">
  <img src="https://readme-typing-svg.herokuapp.com?font=Fira+Code&size=30&duration=3000&pause=1000&color=5865F2&center=true&vCenter=true&width=600&lines=Hey+there!+I'm+{{USER_NAME}}+%F0%9F%91%8B" alt="Typing SVG" />
</div>

<br/>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=waving&color=5865F2&height=120&section=header&text={{USER_NAME}}&fontSize=50&fontColor=fff&animation=twinkling&fontAlignY=35" alt="Header" />
</div>

<br/>

## 💻 Tech Stack

{{TOP_LANGUAGES}}

<br/>

## 📊 GitHub Stats

<div align="center">
  <img src="./assets/github-metrics.svg" alt="GitHub Metrics" />
</div>

<br/>

---

## 🚀 What I'm Working On

{{WORKING_ON}}

<br/>

## 🌱 Latest Projects

{{LATEST_PROJECTS}}

<br/>

## 🔨 Recent Contributions

{{RECENT_PRS}}

<br/>

## ⭐ Recently Starred

{{RECENT_STARS}}

<br/>

---

## 💬 Let's Connect

{{SOCIAL_LINKS}}

<br/>

<div align="center">
  <img src="https://capsule-render.vercel.app/api?type=waving&color=5865F2&height=120&section=footer" alt="Footer" />
</div>
