name: GitHub Metrics
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight UTC
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GH_PAT }}  # REQUIRED for your account
          user: dacrab  # 👈 Your GitHub username
          
          # Display configuration
          template: classic
          base: header, activity, repositories, metadata
          config_timezone: Europe/Athens
          
          # Content plugins
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_limit: 8
          plugin_achievements: yes
          plugin_activity: yes