name: Simple GitHub Stats
on:
  schedule:
    - cron: "0 0 * * *"  # Daily at midnight
  workflow_dispatch:

jobs:
  update-stats:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          
      - name: Generate Simple Stats
        run: |
          echo "<!-- Generated on $(date) -->" > github-metrics.svg
          echo "<!-- Simple GitHub stats for dacrab -->" >> github-metrics.svg
          echo "<!-- Use README stats badges instead -->" >> github-metrics.svg
        
      - name: Commit changes  
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: "📊 Update simple GitHub stats"
          file_pattern: github-metrics.svg
