name: Metrics
on:
  schedule: [{cron: "0 2 * * *"}]  # Run at 2 AM to avoid conflicts
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Remove existing metrics
        run: rm -f github-metrics.svg
        
      - name: Generate metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dacrab
          filename: github-metrics.svg
          template: classic
          base: header, activity, community, repositories, metadata
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_activity: yes
          config_timezone: Europe/Athens
          
      - name: Commit metrics
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '📊 Update GitHub metrics'
          file_pattern: 'github-metrics.svg'
          commit_user_name: 'metrics-bot'
          commit_user_email: 'actions@github.com'
