name: Metrics
on:
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dacrab
          filename: github-metrics.svg
          template: classic
          plugin_lines: yes
          plugin_isocalendar: yes
          plugin_languages: yes
          plugin_activity: yes
          config_timezone: Europe/Athens
