name: Generate Profile README
on:
  push:
    branches: [main]
  schedule:
    - cron: "0 */6 * * *"
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          
      - name: Generate README with metrics
        uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          user: dacrab
          template: classic
          base: header, activity, community, repositories
          config_timezone: Europe/Athens
          
          # Plugins
          plugin_isocalendar: yes
          plugin_isocalendar_duration: full-year
          
          plugin_languages: yes
          plugin_languages_analysis_timeout: 15
          plugin_languages_categories: markup, programming
          plugin_languages_colors: github
          plugin_languages_limit: 8
          plugin_languages_recent_categories: markup, programming
          plugin_languages_recent_days: 14
          plugin_languages_recent_load: 300
          plugin_languages_sections: most-used
          plugin_languages_threshold: 0%
          
          plugin_activity: yes
          plugin_activity_days: 14
          plugin_activity_filter: all
          plugin_activity_limit: 5
          plugin_activity_load: 300
          plugin_activity_visibility: all
          
          plugin_lines: yes
          plugin_lines_history_limit: 1
          plugin_lines_repositories_limit: 4
          plugin_lines_sections: base
          
          # Static content (profile info)
          extras_css: |
            h1, h2 { color: #58a6ff !important; }
          
          # Output
          filename: profile-summary.svg
          
      - name: Create static README content
        run: |
          cat > README.md << 'EOF'
          ## Hi there 👋 I'm Vaggelis Kavouras
          
          [![](https://readme-typing-svg.herokuapp.com/?lines=Welcome+to+my+GitHub+profile!;I'm+a+passionate+solo+developer;Always+learning+new+things&font=Fira%40Code&center=true)](https://github.com/dacrab)
          
          ### About Me
          
          I'm a solo developer from 🇬🇷 Greece with a passion for building modern web apps. I started with C and static websites — and now I create type-safe, full-stack, real-time apps using cutting-edge tools like Supabase, Next.js, and Tailwind CSS.
          
          I enjoy clean design, scalable code, and collaborating with like-minded devs. Always learning. Always shipping.
          🌍 Based in Greece
          
          ### 🛠️ Skills
          
          [![Supabase](https://img.shields.io/badge/Supabase-3ECF8E?style=for-the-badge&logo=supabase&logoColor=white)](https://supabase.com/)
          [![Next.js](https://img.shields.io/badge/Next.js-000000?style=for-the-badge&logo=next.js&logoColor=white)](https://nextjs.org/)
          [![React](https://img.shields.io/badge/React-20232A?style=for-the-badge&logo=react&logoColor=61DAFB)](https://reactjs.org/)
          [![Vite](https://img.shields.io/badge/Vite-646CFF?style=for-the-badge&logo=vite&logoColor=white)](https://vitejs.dev/)
          [![shadcn/ui](https://img.shields.io/badge/shadcn/ui-000000?style=for-the-badge&logo=shadcn&logoColor=white)](https://ui.shadcn.com/)
          [![Tailwind CSS](https://img.shields.io/badge/TailwindCSS-06B6D4?style=for-the-badge&logo=tailwind-css&logoColor=white)](https://tailwindcss.com/)
          [![TypeScript](https://img.shields.io/badge/TypeScript-3178C6?style=for-the-badge&logo=typescript&logoColor=white)](https://www.typescriptlang.org/)
          
          ### 🚀 Featured Projects
          
          | Project | Description | Tech Stack |
          |---------|-------------|------------|
          | 🎯 [**Argicon**](https://argicon.gr) | Sleek architecture studio site with multilingual support and Framer Motion animations | Next.js, Framer Motion, i18n |
          | 🧱 [**DesignDash**](https://designdash.gr) | Bilingual architecture portfolio with light/dark mode | Next.js, Tailwind CSS |
          | 🧑‍💼 [**clubOS**](https://clubos.vercel.app) | POS and booking system for sports facilities with real-time data, RBAC, and analytics | [Repo](https://github.com/dacrab/clubos) |
          | 🌐 [**Portfolio**](https://dacrab.github.io/) | Personal developer portfolio | Next.js, TypeScript, TailwindCSS [Repo](https://github.com/dacrab/portfolio) |
          
          ### 📊 GitHub Stats
          
          <div align="center">
          
          ![Profile Summary](profile-summary.svg)
          
          </div>
          
          <div align="center">
          
          [![GitHub stats](https://github-readme-stats.vercel.app/api?username=dacrab&show_icons=true&theme=tokyonight&hide_border=true&bg_color=0D1117)](https://github.com/dacrab)
          
          [![GitHub Streak](https://github-readme-streak-stats.herokuapp.com/?user=dacrab&theme=tokyonight&hide_border=true&background=0D1117)](https://github.com/dacrab)
          
          [![Top Languages](https://github-readme-stats.vercel.app/api/top-langs/?username=dacrab&layout=compact&theme=tokyonight&hide_border=true&bg_color=0D1117)](https://github.com/dacrab)
          
          [![Activity Graph](https://github-readme-activity-graph.vercel.app/graph?username=dacrab&theme=react-dark&hide_border=true&bg_color=0D1117)](https://github.com/dacrab)
          
          </div>
          
          ### 🤝 Let's Connect!
          
          <div align="center">
          
          [![Instagram](https://img.shields.io/badge/Instagram-E4405F?style=for-the-badge&logo=instagram&logoColor=white)](https://www.instagram.com/killcrb/)
          [![GitHub](https://img.shields.io/badge/GitHub-100000?style=for-the-badge&logo=github&logoColor=white)](https://github.com/dacrab)
          [![LinkedIn](https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white)](https://www.linkedin.com/in/vkavouras/)
          
          </div>
          
          ---
          
          <div align="center">
          
          **✨ Always learning, always building, always shipping! ✨**
          
          *Last updated: $(date '+%B %d, %Y')*
          
          </div>
          EOF
          
      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: '🔄 Auto-update profile README'
          file_pattern: 'README.md profile-summary.svg'
          commit_user_name: 'github-actions[bot]'
          commit_user_email: '41898282+github-actions[bot]@users.noreply.github.com'
