name: Update Dynamic README Content

on:
  # Schedule updates (every 6 hours)
  schedule: 
    - cron: "0 */6 * * *"
  # Allow manual triggering
  workflow_dispatch:
  # Trigger on pushes to main (but only if certain files change)
  push:
    branches: ["main"]
    paths: 
      - 'config.js'
      - 'scripts/generate.js' 
      - 'README.gtpl'

jobs:
  update-readme:
    runs-on: ubuntu-latest
    
    permissions:
      contents: write
      
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Generate README with latest data
        run: npm run generate
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PAT }}
          
      - name: Check for changes
        id: git-check
        run: |
          git diff --exit-code README.md || echo "changed=true" >> $GITHUB_OUTPUT
          
      - name: Commit updated README
        if: steps.git-check.outputs.changed == 'true'
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add README.md
          git commit -m "🔄 Auto-update dynamic README content
          
          ✨ Updated sections:
          - Currently working on repositories  
          - Latest projects
          - Recent pull requests
          - Recent stars
          - Technology stack
          - Contact information
          
          Generated: $(date -u '+%Y-%m-%d %H:%M:%S UTC')"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
